export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'

export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY'
export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD'

export const ADD_TO_CART = 'ADD_TO_CART'
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY'
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
